spring.datasource.url=jdbc:mysql://localhost:3306/iot_locker
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# The overview strictly defines ddl-auto=validate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true